// packages/vue/src/components/DialogProductBlock/DialogProductBlock.vue
<template>
  <ThemeProvider :theme="props.client.theme">
    <div id="dialog-instant" class="dialog-block-container" :dir="direction">
      <DialogBlockHeader :title="assistantName" :description="description" />
      <DialogBlockSuggestionsContainer
        :client="props.client"
        :questions="suggestionData?.questions"
        :is-loading="isFetchingSuggestions"
        :product-id="props.productId"
        :product-title="props.productTitle"
        :selected-variant-id="props?.selectedVariantId"
      />
      <DialogInput
        v-if="props.enableInput"
        :client="props.client"
        :placeholder="inputPlaceholder"
        :product-id="props.productId"
        :product-title="props.productTitle"
        :selected-variant-id="props?.selectedVariantId"
      />
    </div>
  </ThemeProvider>
</template>

<script setup lang="ts">
import {
  addAuditCapability,
  Dialog,
  registerDialogInstallation,
  resolveTextDirection,
  type Suggestion,
} from "@askdialog/dialog-sdk";
import DialogBlockHeader from "./DialogBlockHeader.vue";
import DialogBlockSuggestionsContainer from "./DialogBlockSuggestionsContainer.vue";
import DialogInput from "./DialogInput.vue";
import ThemeProvider from "./ThemeProvider.vue";
import { computed, onMounted, ref, watch } from "vue";

interface Props {
  client: Dialog;
  productId: string;
  productTitle: string;
  selectedVariantId?: string;
  /** @deprecated Use the default "Ask something else" button. */
  enableInput?: boolean;
}

const props = withDefaults(defineProps<Props>(), {
  enableInput: false,
  selectedVariantId: undefined,
});

onMounted(() => {
  registerDialogInstallation({
    method: "vue",
    version:
      typeof __DIALOG_VUE_VERSION__ === "undefined"
        ? undefined
        : __DIALOG_VUE_VERSION__,
  });
  addAuditCapability("pdp-block");
});
const isFetchingSuggestions = ref(true);
const suggestionData = ref<Suggestion | undefined>(undefined);
const fetchSequence = ref(0);

const assistantName = computed(() => {
  return isFetchingSuggestions.value ? "" : suggestionData.value?.assistantName;
});
const description = computed(() => {
  return isFetchingSuggestions.value ? "" : suggestionData.value?.description;
});
const inputPlaceholder = computed(() => {
  return isFetchingSuggestions.value
    ? ""
    : suggestionData.value?.inputPlaceholder;
});

const direction = computed(() =>
  resolveTextDirection(
    props.client.getLocalizationInformations()?.languageCode,
  ),
);

const handleFetchingSuggestions = async () => {
  const sequence = ++fetchSequence.value;
  isFetchingSuggestions.value = true;
  suggestionData.value = undefined;
  try {
    const suggestion = await props.client.getSuggestions(props.productId);
    if (sequence === fetchSequence.value) {
      suggestionData.value = suggestion;
    }
  } catch (error) {
    console.error("error", error);
  } finally {
    if (sequence === fetchSequence.value) {
      isFetchingSuggestions.value = false;
    }
  }
};

watch(
  () => [props.client, props.productId] as const,
  () => {
    void handleFetchingSuggestions();
  },
  { immediate: true },
);
</script>

<style scoped>
.dialog-block-container {
  position: relative;
  display: flex;
  flex-direction: column;
  justify-content: flex-start;
  align-items: flex-start;
  padding: 24px 0;
  width: fit-content;
  gap: 24px;
}
.dialog-block-container > * {
  box-sizing: border-box;
}
</style>

// packages/react/src/components/DialogProductBlock/DialogProductBlock.tsx
import { type FC, useEffect, useState, useMemo } from "react";
import {
  addAuditCapability,
  registerDialogInstallation,
  resolveTextDirection,
  type Suggestion,
} from "@askdialog/dialog-sdk";
import type { Dialog } from "@askdialog/dialog-sdk";
import { DialogBlockHeader } from "./DialogBlockHeader";
import { DialogBlockSuggestionsContainer } from "./DialogBlockSuggestionsContainer";
import { DialogInput } from "./DialogInput";
import { ThemeProvider } from "./ThemeProvider";
import "./DialogProductBlock.css";

interface DialogProductBlockProps {
  client: Dialog;
  productId: string;
  productTitle: string;
  selectedVariantId?: string;
  /** @deprecated Use the default "Ask something else" button. */
  enableInput?: boolean;
}

export const DialogProductBlock: FC<DialogProductBlockProps> = ({
  client,
  productId,
  productTitle,
  selectedVariantId,
  enableInput = false,
}) => {
  const [isFetchingSuggestions, setIsFetchingSuggestions] = useState(true);
  const [suggestionData, setSuggestionData] = useState<Suggestion | undefined>(
    undefined,
  );

  useEffect(() => {
    registerDialogInstallation({
      method: "react",
      version:
        typeof __DIALOG_REACT_VERSION__ === "undefined"
          ? undefined
          : __DIALOG_REACT_VERSION__,
    });
    addAuditCapability("pdp-block");
  }, []);

  const assistantName = useMemo(
    () => (isFetchingSuggestions ? "" : suggestionData?.assistantName),
    [suggestionData, isFetchingSuggestions],
  );
  const description = useMemo(
    () => (isFetchingSuggestions ? "" : suggestionData?.description),
    [suggestionData, isFetchingSuggestions],
  );
  const inputPlaceholder = useMemo(
    () => (isFetchingSuggestions ? "" : suggestionData?.inputPlaceholder),
    [suggestionData, isFetchingSuggestions],
  );

  const direction = useMemo(
    () =>
      resolveTextDirection(client.getLocalizationInformations()?.languageCode),
    [client],
  );

  useEffect(() => {
    let isActive = true;
    const handleFetchingSuggestions = async (): Promise<void> => {
      setIsFetchingSuggestions(true);
      setSuggestionData(undefined);
      try {
        const suggestion = await client.getSuggestions(productId);
        if (isActive) {
          setSuggestionData(suggestion);
        }
      } catch (error) {
        console.error("error", error);
      } finally {
        if (isActive) {
          setIsFetchingSuggestions(false);
        }
      }
    };

    handleFetchingSuggestions();
    return () => {
      isActive = false;
    };
  }, [client, productId]);

  return (
    <ThemeProvider theme={client.theme}>
      <div
        id="dialog-instant"
        className="dialog-block-container"
        dir={direction}
      >
        <DialogBlockHeader title={assistantName} description={description} />
        <DialogBlockSuggestionsContainer
          client={client}
          questions={suggestionData?.questions}
          isLoading={isFetchingSuggestions}
          productId={productId}
          productTitle={productTitle}
          selectedVariantId={selectedVariantId}
        />
        {enableInput && (
          <DialogInput
            client={client}
            placeholder={inputPlaceholder}
            productId={productId}
            productTitle={productTitle}
            selectedVariantId={selectedVariantId}
          />
        )}
      </div>
    </ThemeProvider>
  );
};
