// packages/react/src/components/DialogProductBlock/DialogBlockSuggestionsContainer.tsx
import type { FC } from "react";
import type { Dialog, Suggestion } from "@askdialog/dialog-sdk";
import { DialogBlockSuggestions } from "./DialogBlockSuggestions";
import { DialogBlockSuggestionsSkeleton } from "./DialogBlockSuggestionsSkeleton";
import "./DialogBlockSuggestionsContainer.css";

interface DialogBlockSuggestionsContainerProps {
  client: Dialog;
  questions: Suggestion["questions"] | undefined;
  isLoading: boolean;
  productId: string;
  productTitle: string;
  selectedVariantId?: string;
}

export const DialogBlockSuggestionsContainer: FC<
  DialogBlockSuggestionsContainerProps
> = ({
  client,
  questions,
  isLoading,
  productId,
  productTitle,
  selectedVariantId,
}) => {
  return (
    <div className="dialog-block-suggestions-container">
      {isLoading || !questions ? (
        <DialogBlockSuggestionsSkeleton />
      ) : (
        <DialogBlockSuggestions
          client={client}
          questions={questions}
          productId={productId}
          productTitle={productTitle}
          selectedVariantId={selectedVariantId}
        />
      )}
    </div>
  );
};

// packages/vue/src/components/DialogProductBlock/DialogBlockSuggestionsContainer.vue
<template>
  <div class="dialog-block-suggestions-container">
    <DialogBlockSuggestionsSkeleton
      v-if="props.isLoading || !props.questions"
    />
    <DialogBlockSuggestions
      v-else
      :client="props.client"
      :questions="props.questions"
      :product-id="props.productId"
      :product-title="props.productTitle"
      :selected-variant-id="props.selectedVariantId"
    />
  </div>
</template>

<script setup lang="ts">
import type { Dialog, Suggestion } from "@askdialog/dialog-sdk";
import DialogBlockSuggestions from "./DialogBlockSuggestions.vue";
import DialogBlockSuggestionsSkeleton from "./DialogBlockSuggestionsSkeleton.vue";

const props = defineProps<{
  client: Dialog;
  questions: Suggestion["questions"] | undefined;
  isLoading: boolean;
  productId: string;
  productTitle: string;
  selectedVariantId?: string;
}>();
</script>

<style scoped>
.dialog-block-suggestions-container {
  display: flex;
  flex-direction: column;
  gap: 12px;
  width: 100%;
}
</style>
