// packages/react/src/components/DialogProductBlock/DialogInput.tsx
import { type FC, useRef, useState, type KeyboardEvent } from "react";
import type { Dialog } from "@askdialog/dialog-sdk";
import { ArrowIcon } from "../../icons/ArrowIcon";
import { getInputMessages } from "./inputMessages";
import "./DialogInput.css";

interface DialogInputProps {
  client: Dialog;
  /** @deprecated Ignored: the input always shows the fixed AI text. */
  placeholder?: string;
  productId: string;
  productTitle: string;
  selectedVariantId?: string;
}

export const DialogInput: FC<DialogInputProps> = ({
  client,
  productId,
  productTitle,
  selectedVariantId,
}) => {
  const inputRef = useRef<HTMLInputElement>(null);
  const [inputValue, setInputValue] = useState("");
  const messages = getInputMessages(client.locale);

  const focusInput = (): void => {
    inputRef.current?.focus();
  };

  const handleSubmitQuestion = (): void => {
    const question = inputValue;
    if (!question.trim()) {
      return;
    }

    client.sendProductMessage({
      productId,
      productTitle,
      selectedVariantId,
      question,
      fromQuestionSuggestion: true,
    });
    setInputValue("");
  };

  const handleKeyDown = (e: KeyboardEvent<HTMLInputElement>): void => {
    if (e.key === "Enter") {
      handleSubmitQuestion();
    }
  };

  return (
    <div className="dialog-input-container">
      <div className="dialog-input-wrapper" onClick={focusInput}>
        <input
          id="dialog-ask-anything-input-ai-input"
          ref={inputRef}
          value={inputValue}
          onChange={(e) => setInputValue(e.target.value)}
          className="dialog-ask-anything-input-ai-input"
          placeholder={messages.placeholder}
          aria-describedby="dialog-input-ai-disclosure"
          onKeyDown={handleKeyDown}
        />

        <button
          id="send-message-button-ai-input"
          className="dialog-input-submit"
          disabled={!inputValue.trim()}
          onClick={handleSubmitQuestion}
        >
          <ArrowIcon color={client.theme.ctaTextColor} />
        </button>
      </div>
      <p id="dialog-input-ai-disclosure" className="dialog-input-ai-disclosure">
        {messages.aiDisclosure}
      </p>
    </div>
  );
};

// packages/vue/src/components/DialogProductBlock/DialogInput.vue
<template>
  <div class="dialog-input-container">
    <div class="dialog-input-wrapper" @click="focusInput">
      <input
        id="dialog-ask-anything-input-ai-input"
        ref="inputRef"
        v-model="inputValue"
        class="dialog-ask-anything-input-ai-input"
        :placeholder="messages.placeholder"
        aria-describedby="dialog-input-ai-disclosure"
        @keydown.enter="handleSubmitQuestion"
      />

      <button
        id="send-message-button-ai-input"
        class="dialog-input-submit"
        :disabled="!inputValue.trim()"
        @click="handleSubmitQuestion"
      >
        <ArrowIcon :color="props.client.theme.ctaTextColor" />
      </button>
    </div>
    <p id="dialog-input-ai-disclosure" class="dialog-input-ai-disclosure">
      {{ messages.aiDisclosure }}
    </p>
  </div>
</template>

<script setup lang="ts">
import type { Dialog } from "@askdialog/dialog-sdk";
import ArrowIcon from "../../icons/ArrowIcon.vue";
import { computed, ref } from "vue";
import { getInputMessages } from "./inputMessages";

interface Props {
  client: Dialog;
  /** @deprecated Ignored: the input always shows the fixed AI text. */
  placeholder?: string;
  productId: string;
  productTitle: string;
  selectedVariantId?: string;
}

const props = defineProps<Props>();
const inputRef = ref<HTMLInputElement>();
const inputValue = ref("");
const messages = computed(() => getInputMessages(props.client.locale));

const focusInput = () => {
  inputRef.value?.focus();
};

const handleSubmitQuestion = () => {
  const question = inputValue.value;
  if (!question.trim()) {
    return;
  }

  props.client.sendProductMessage({
    productId: props.productId,
    productTitle: props.productTitle,
    selectedVariantId: props.selectedVariantId,
    question: question,
    fromQuestionSuggestion: true,
  });
  inputValue.value = "";
};
</script>

<style scoped>
.dialog-input-wrapper {
  position: relative;
  width: 100%;
  height: 50px;
  max-height: 50px;
  padding: 16px 20px;
  border: 1px solid #d9d9d9;
  border-radius: var(--dialog-theme-cta-border-type, 24px);
  background: #ffffff;
  display: flex;
  align-items: center;
  box-sizing: border-box;
}

.dialog-input-container {
  display: flex;
  flex-direction: column;
  gap: 8px;
  width: 100%;
}

.dialog-ask-anything-input-ai-input {
  outline: unset;
  box-shadow: unset;
  border: unset;
  width: 100%;
  font-size: 16px;
  background: transparent;
  padding-inline-end: 35px;
}

.dialog-input-submit {
  width: 40px;
  height: 40px;
  border-radius: 100%;
  display: flex;
  align-items: center;
  justify-content: center;
  background-color: var(--dialog-theme-primary-color);
  position: absolute;
  cursor: pointer;
  top: calc(50% - 20px);
  inset-inline-end: 4px;
  border: unset;
}
.dialog-input-submit:disabled {
  opacity: 0.5;
}

.dialog-input-ai-disclosure {
  margin: 0;
  font-size: 12px;
  line-height: 1.4;
  color: #6b6b6b;
}
</style>
