// packages/react/src/components/DialogProductBlock/DialogBlockSuggestions.tsx
import type { FC } from "react";
import type { Dialog, Suggestion } from "@askdialog/dialog-sdk";
import { AiStarsIcon } from "../../icons/AiStarsIcon";
import "./DialogBlockSuggestions.css";

interface DialogBlockSuggestionsProps {
  client: Dialog;
  questions: Suggestion["questions"];
  productId: string;
  productTitle: string;
  selectedVariantId?: string;
}

export const DialogBlockSuggestions: FC<DialogBlockSuggestionsProps> = ({
  client,
  questions,
  productId,
  productTitle,
  selectedVariantId,
}) => {
  const handleClick = (question: string): void => {
    client.sendProductMessage({
      productId,
      productTitle,
      selectedVariantId,
      question,
      fromQuestionSuggestion: true,
    });
  };

  return (
    <>
      {questions.map((question) => (
        <button
          key={question.question}
          className="dialog-block-suggestions-item"
          onClick={() => handleClick(question.question)}
        >
          <AiStarsIcon color={client.theme.primaryColor} />
          <span className="dialog-block-suggestions-item-label">
            {question.question}
          </span>
        </button>
      ))}
    </>
  );
};

// packages/vue/src/components/DialogProductBlock/DialogBlockSuggestions.vue
<template>
  <button
    v-for="question in props.questions"
    :key="question.question"
    class="dialog-block-suggestions-item"
    @click="handleClick(question.question)"
  >
    <AiStarsIcon
      class="dialog-block-suggestions-item-icon"
      :color="props.client.theme.primaryColor"
    />
    <span class="dialog-block-suggestions-item-label">
      {{ question.question }}
    </span>
  </button>
</template>

<script setup lang="ts">
import type { Dialog, Suggestion } from "@askdialog/dialog-sdk";
import AiStarsIcon from "../../icons/AiStarsIcon.vue";

const props = defineProps<{
  client: Dialog;
  questions: Suggestion["questions"];
  productId: string;
  productTitle: string;
  selectedVariantId?: string;
}>();

const handleClick = (question: string) => {
  props.client.sendProductMessage({
    productId: props.productId,
    productTitle: props.productTitle,
    selectedVariantId: props.selectedVariantId,
    question: question,
    fromQuestionSuggestion: true,
  });
};
</script>

<style scoped>
.dialog-block-suggestions-item {
  border-radius: 18px;
  background-color: #f1f1f1;
  border: none;
  outline: none;
  padding: 12px 16px;
  width: fit-content;
  cursor: pointer;
  display: flex;
  justify-content: flex-start;
  background-color: white;
  align-items: center;
  gap: 8px;
  border: 1px solid #dddce2;
  border-radius: 24px;
}
.dialog-block-suggestions-item:hover {
  transform: scale(1.01);
}
.dialog-block-suggestions-item-label {
  color: var(--dialog-theme-content-color, #575665);
  font-size: var(--dialog-theme-content-font-size, 14px);
  font-weight: 500;
  text-align: start;
  flex: 1;
}
.dialog-block-suggestions-item-icon {
  path {
    stroke: var(--dialog-theme-primary-color);
  }
}
</style>
