// packages/vue/src/components/DialogSearch/DialogSearchResults.vue
<template>
  <div ref="anchorRef" />
  <Teleport v-if="showPanel" to="body">
    <div ref="panelRef" class="dialog-search-panel" :style="panelStyle">
      <p
        v-if="props.state.status === SearchStatus.LOADING"
        role="status"
        class="dialog-search-status"
      >
        Searching “{{ props.state.query }}”…
      </p>
      <div
        v-else-if="props.state.status === SearchStatus.ERROR"
        class="dialog-search-error"
      >
        <p role="alert" class="dialog-search-status dialog-search-status-error">
          {{ describeError(props.state.error) }}
        </p>
        <button
          type="button"
          class="dialog-search-retry"
          @click="props.controller.retry()"
        >
          Retry
        </button>
      </div>
      <p
        v-else-if="props.state.status === SearchStatus.EMPTY"
        role="status"
        class="dialog-search-status"
      >
        No products match “{{ props.state.response?.query }}”.
      </p>
      <template
        v-else-if="
          props.state.status === SearchStatus.SUCCESS &&
          props.state.response !== undefined
        "
      >
        <p role="status" class="dialog-search-status">
          {{ props.state.response.nbHits }}
          result{{ props.state.response.nbHits > 1 ? "s" : "" }}
        </p>
        <ul class="dialog-search-results">
          <DialogSearchProductCard
            v-for="(hit, index) in props.state.response.hits"
            :key="hit.objectID"
            :controller="props.controller"
            :hit="hit"
            :index="index"
            :locale="props.locale"
          />
        </ul>
        <DialogSearchPagination
          :controller="props.controller"
          :state="props.state"
        />
      </template>
    </div>
  </Teleport>
</template>

<script setup lang="ts">
import {
  DialogSearchError,
  SearchStatus,
  type SearchController,
  type SearchControllerState,
} from "@askdialog/dialog-sdk";
import { computed, type CSSProperties } from "vue";
import DialogSearchPagination from "./DialogSearchPagination.vue";
import DialogSearchProductCard from "./DialogSearchProductCard.vue";
import { useAnchorRect, type AnchorRect } from "./useAnchorRect";
import { useOutsideDismiss } from "./useOutsideDismiss";

const PANEL_OFFSET_PX = 8;
const VIEWPORT_MARGIN_PX = 16;
// Below this available height the panel flips above the bar when there is
// more room there — otherwise a bar near the viewport bottom leaves the
// panel zero or negative height.
const MIN_PANEL_SPACE_PX = 200;

interface Props {
  controller: SearchController;
  state: SearchControllerState;
  locale?: string;
}

const props = defineProps<Props>();

const describeError = (error: unknown): string => {
  if (error instanceof DialogSearchError) {
    return `Search failed (${error.status}${error.code ? ` ${error.code}` : ""}): ${error.message}`;
  }

  return "Search failed: network error. Check your connection and try again.";
};

const isAnchorOnScreen = (rect: AnchorRect, viewportHeight: number): boolean =>
  rect.bottom > 0 && rect.top < viewportHeight;

const computePanelStyle = (
  rect: AnchorRect,
  viewportHeight: number,
): CSSProperties => {
  const spaceBelow =
    viewportHeight - rect.bottom - PANEL_OFFSET_PX - VIEWPORT_MARGIN_PX;
  const spaceAbove = rect.top - PANEL_OFFSET_PX - VIEWPORT_MARGIN_PX;
  const base = { left: `${rect.left}px`, width: `${rect.width}px` };

  if (spaceBelow < MIN_PANEL_SPACE_PX && spaceAbove > spaceBelow) {
    return {
      ...base,
      bottom: `${viewportHeight - rect.top + PANEL_OFFSET_PX}px`,
      maxHeight: `${Math.max(spaceAbove, 0)}px`,
    };
  }

  return {
    ...base,
    top: `${rect.bottom + PANEL_OFFSET_PX}px`,
    maxHeight: `${Math.max(spaceBelow, 0)}px`,
  };
};

const stateRef = computed(() => props.state);
const hasResults = computed(() => props.state.status !== SearchStatus.IDLE);

// The panel is teleported to document.body in position: fixed so no ancestor
// stacking context or overflow clipping can hide it; the in-flow anchor div
// (rendered right after the bar) provides its coordinates.
const { anchorRef, rect, viewportHeight } = useAnchorRect(hasResults);
const { isOpen, panelRef } = useOutsideDismiss(stateRef, anchorRef);

const showPanel = computed(
  () =>
    isOpen.value &&
    rect.value !== undefined &&
    isAnchorOnScreen(rect.value, viewportHeight.value),
);
const panelStyle = computed(() =>
  rect.value === undefined
    ? undefined
    : computePanelStyle(rect.value, viewportHeight.value),
);
</script>

<style>
/* Teleported to document.body; top/left/width/max-height are set inline from the anchor. */
.dialog-search-panel {
  position: fixed;
  z-index: 9999;
  box-sizing: border-box;
  display: flex;
  flex-direction: column;
  gap: 8px;
  margin: 0;
  padding: 10px 14px;
  background: rgba(255, 255, 255, 0.9);
  backdrop-filter: blur(12px);
  -webkit-backdrop-filter: blur(12px);
  border: 1px solid rgba(0, 0, 0, 0.05);
  border-radius: 24px;
  box-shadow: 0 6px 20px -6px rgba(0, 0, 0, 0.1);
}

.dialog-search-status {
  margin: 0;
  font-family: "Inter", sans-serif;
  font-weight: 500;
  font-size: 14px;
  line-height: 20px;
  color: #a3a3a3;
}

.dialog-search-status-error {
  color: #b3261e;
}

.dialog-search-error {
  display: flex;
  flex-direction: column;
  align-items: flex-start;
  gap: 8px;
}

.dialog-search-retry {
  margin: 0;
  padding: 6px 14px;
  border: 1px solid rgba(0, 0, 0, 0.05);
  border-radius: 9999px;
  background: #ffffff;
  font-family: "Inter", sans-serif;
  font-weight: 500;
  font-size: 13px;
  line-height: 20px;
  color: #737373;
  cursor: pointer;
  transition: background-color 120ms ease;
}

.dialog-search-retry:hover {
  background-color: #fafafa;
}

.dialog-search-results {
  display: flex;
  flex-direction: column;
  gap: 12px;
  margin: 0;
  padding: 0;
  list-style: none;
  max-height: 480px;
  min-height: 0;
  overflow-y: auto;
}
</style>

// packages/react/src/components/DialogSearch/DialogSearchResults.tsx
import type { CSSProperties, FC, ReactNode } from "react";
import { createPortal } from "react-dom";
import {
  DialogSearchError,
  SearchStatus,
  type SearchController,
  type SearchControllerState,
} from "@askdialog/dialog-sdk";
import { DialogSearchPagination } from "./DialogSearchPagination";
import { DialogSearchProductCard } from "./DialogSearchProductCard";
import { useAnchorRect, type AnchorRect } from "./useAnchorRect";
import { useOutsideDismiss } from "./useOutsideDismiss";
import "./DialogSearchResults.css";

const PANEL_OFFSET_PX = 8;
const VIEWPORT_MARGIN_PX = 16;
// Below this available height the panel flips above the bar when there is
// more room there — otherwise a bar near the viewport bottom leaves the
// panel zero or negative height.
const MIN_PANEL_SPACE_PX = 200;

interface DialogSearchResultsProps {
  controller: SearchController;
  state: SearchControllerState;
  locale?: string;
}

const describeError = (error: unknown): string => {
  if (error instanceof DialogSearchError) {
    return `Search failed (${error.status}${error.code ? ` ${error.code}` : ""}): ${error.message}`;
  }

  return "Search failed: network error. Check your connection and try again.";
};

const isAnchorOnScreen = (rect: AnchorRect, viewportHeight: number): boolean =>
  rect.bottom > 0 && rect.top < viewportHeight;

const panelStyle = (
  rect: AnchorRect,
  viewportHeight: number,
): CSSProperties => {
  const spaceBelow =
    viewportHeight - rect.bottom - PANEL_OFFSET_PX - VIEWPORT_MARGIN_PX;
  const spaceAbove = rect.top - PANEL_OFFSET_PX - VIEWPORT_MARGIN_PX;
  const base = { left: rect.left, width: rect.width };

  if (spaceBelow < MIN_PANEL_SPACE_PX && spaceAbove > spaceBelow) {
    return {
      ...base,
      bottom: viewportHeight - rect.top + PANEL_OFFSET_PX,
      maxHeight: Math.max(spaceAbove, 0),
    };
  }

  return {
    ...base,
    top: rect.bottom + PANEL_OFFSET_PX,
    maxHeight: Math.max(spaceBelow, 0),
  };
};

const panelContent = (
  controller: SearchController,
  state: SearchControllerState,
  locale: string | undefined,
): ReactNode => {
  const response = state.response;

  switch (state.status) {
    case SearchStatus.LOADING:
      return (
        <p role="status" className="dialog-search-status">
          Searching “{state.query}”…
        </p>
      );
    case SearchStatus.ERROR:
      return (
        <div className="dialog-search-error">
          <p
            role="alert"
            className="dialog-search-status dialog-search-status-error"
          >
            {describeError(state.error)}
          </p>
          <button
            type="button"
            className="dialog-search-retry"
            onClick={() => controller.retry()}
          >
            Retry
          </button>
        </div>
      );
    case SearchStatus.EMPTY:
      return (
        <p role="status" className="dialog-search-status">
          No products match “{response?.query}”.
        </p>
      );
    case SearchStatus.SUCCESS:
      if (response === undefined) {
        return null;
      }

      return (
        <>
          <p role="status" className="dialog-search-status">
            {response.nbHits} result{response.nbHits > 1 ? "s" : ""}
          </p>
          <ul className="dialog-search-results">
            {response.hits.map((hit, index) => (
              <DialogSearchProductCard
                key={hit.objectID}
                controller={controller}
                hit={hit}
                index={index}
                locale={locale}
              />
            ))}
          </ul>
          <DialogSearchPagination controller={controller} state={state} />
        </>
      );
    default:
      return null;
  }
};

// The panel is portaled to document.body in position: fixed so no ancestor
// stacking context or overflow clipping can hide it; the in-flow anchor div
// (rendered right after the bar) provides its coordinates.
export const DialogSearchResults: FC<DialogSearchResultsProps> = ({
  controller,
  state,
  locale,
}) => {
  const hasResults = state.status !== SearchStatus.IDLE;
  const { anchorRef, rect, viewportHeight } = useAnchorRect(hasResults);
  const { isOpen, panelRef } = useOutsideDismiss(state, anchorRef);

  return (
    <>
      <div ref={anchorRef} />
      {isOpen &&
        rect !== undefined &&
        isAnchorOnScreen(rect, viewportHeight) &&
        createPortal(
          <div
            ref={panelRef}
            className="dialog-search-panel"
            style={panelStyle(rect, viewportHeight)}
          >
            {panelContent(controller, state, locale)}
          </div>,
          document.body,
        )}
    </>
  );
};
